### ISSUE TITLE
Open MV

### ISSUE THREAD

**Issue by odudex** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#100]
I ordered this board specifically to run OpenMV.
I download RT-Thread Studio, and after having a hard time figuring out the Toolchain manager installs arm-gcc 5.4.1, when in fact 10.2.1 is required.
Once I resolved that issue, I could only get the "vision_board_camera" example working; the other examples compile but don't run.
However, the worst part is that OpenMV isn't included. Then I cloned this repo, but RT-Thread Studio fails to compile openMV project, there are many errors. Are you using Keil to build it? How can I get it working?

**Comment by Rbb666** [comment]
1、What do you mean that you can only create the vision_board_camera project successfully, but other projects cannot be created successfully? Can you take a screenshot for me to see?
2、I will update the sdk to a version today. He will be able to use studio to create openmv projects. Of course, it is also possible to use keil.

**Comment by Rbb666** [comment]
## RT-Thread Studio build openmv instructions

If you want to use RT-Thread Studio to create and compile an OpenMV project, you need to strictly follow the following steps:

1. Download the latest Vision Board development board support package in Studio's SDK-Manager (must be >1.1.0 version)

2. Need to switch to Github download source in Studio

![image](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/64397326/a4a60447-aa7b-455e-90b9-757e2aff8cd7)

4. Download V13.2.1 version GCC tool chain

![image](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/64397326/85c6aa05-f142-44dc-8519-fbeaefe24c7a)

5. Enable lifting the command line length limit:

![image](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/64397326/a7894b83-b472-4cbb-b1b7-08318c3ffde3)

**Comment by odudex** [comment]
With GCC 13.2.1 and Vision Board 1.2 OpenMV worked. Thank you!
