### ISSUE TITLE
原理图能给一个kicad的源文件吗？

### ISSUE THREAD

**Issue by chopin1998** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#11]
rt

因为太多层了， pdf的看的好累。。

**Comment by Rbb666** [comment]
> rt
> 
> 因为太多层了， pdf的看的好累。。

可以的，这两天就会提交上来

**Comment by Rbb666** [comment]
关联此PR：https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/pull/15
