### ISSUE TITLE
please help me check the SConscript

### ISSUE THREAD

**Issue by KunYi** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#28]
please check the below 
https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/blob/9c6a6f5207a8a80bbd890cf28734d62ad5fde414/projects/vision_board_openmv/packages/micropython-v1.13.0/SConscript#L43-L47

Line 45 should be change to below, original will failed on link stage
```
group = group + DefineGroup('micropython/machine', machine_src, depend = ['PKG_USING_MICROPYTHON']) 
```

**Comment by Rbb666** [comment]
fix:https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/pull/88
