### ISSUE TITLE
请教MIPI座子型号是什么

### ISSUE THREAD

**Issue by dreamcmi** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#37]
在查看仓库里的kicad原理图时，找到CN2插座的数据手册指向了一个0.3间距的FPC，但是看淘宝的预览图像是0.5的FPC，请问下这个插座的正确型号应该是什么？谢谢。
![2A5E00575E1E81A8BCF9BD595772D765](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/54615441/75d5299b-a9b6-46bc-834f-c1d72b79bbb1)
![Snipaste_2024-03-07_22-28-31](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/54615441/9f0ee2c3-2dc6-4d1c-92ab-9abc5e74bd3e)
![Snipaste_2024-03-07_22-28-44](https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/54615441/e1fce5e9-5e5f-455d-97db-dda6b507f38c)

**Comment by 9527sz** [comment]
您好，原理图数据手册链接有误，正确型号参数应为 SMD,P=0.5mm,下接。

**Comment by dreamcmi** [comment]
thanks
