### ISSUE TITLE
Rt的OpenMV如何驱动液晶屏？

### ISSUE THREAD

**Issue by hexenzhou** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#53]
购买的OpenMV vision board带有液晶屏，Micropython如何驱动这个液晶屏？有相关的demo吗？

**Comment by Rbb666** [comment]
# LCD Example
#
# Note: To run this example you will need a LCD Shield for your OpenMV Cam.
#
# The LCD Shield allows you to view your OpenMV Cam's frame buffer on the go.

import sensor
import time
import lcd

sensor.reset()  # Initialize the camera sensor.
sensor.set_pixformat(sensor.RGB565)  # or sensor.GRAYSCALE
sensor.set_framesize(sensor.QVGA)  # Special 128x160 framesize for LCD Shield.
lcd.init()

# FPS clock
clock = time.clock()

while True:
    clock.tick()
    img = sensor.snapshot()
    img.draw_string(0, 0, "fps:%2.2f" % clock.fps(), color=(255,0,0), scale=1)
    lcd.display(img)  # Take a picture and display the image.
