### ISSUE TITLE
当摄像头设置的分辨率大于LCD分辨率时显示不正常

### ISSUE THREAD

**Issue by hexenzhou** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#65]
摄像头采集分辨率设置VGA以上，LCD显示花屏异常。

代码：
sensor.set_framesize(sensor.VGA) #  640 x 480

原版的OpenMV会自动裁剪居中图像以适应LCD的分辨率。

**Comment by Rbb666** [comment]
欢迎PR！

**Comment by Rbb666** [comment]
> 摄像头采集分辨率设置VGA以上，LCD显示花屏异常。
> 
> 代码： sensor.set_framesize(sensor.VGA) # 640 x 480
> 
> 原版的OpenMV会自动裁剪居中图像以适应LCD的分辨率。

已修复 #69
