### ISSUE TITLE
使用ra配置之后出现memory_regions.ld不存在

### ISSUE THREAD

**Issue by vangao-gg** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#79]
1. 步骤一：使用IDE通过开发板导入vison-board工程；
2. 步骤二：使用ra生成一次代码；
3. 步骤三：回到IDE启动编译，就会出现这个memory_regions.ld不存在的问题；

- 临时解决方法（1）：把memory_regions.ld放到fsa.ld的同级目录下；
- 临时解决方法（2）：修改编译配置中的链接脚本的目录；

<img width="1280" alt="7f86fac084a5cd0c30ba17868ccb3c6" src="https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/assets/91398548/6fd3a6b7-fe8f-4495-8b17-8733335c0d03">

**Comment by Rbb666** [comment]
已修复：https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/pull/77
