### ISSUE TITLE
Connector part number

### ISSUE THREAD

**Issue by TheServer201** [RT-Thread-Studio/sdk-bsp-ra8d1-vision-board#92]
Hi RT-Thread,

What is the part number of the CN5 connector (it seems to be from the G832MB serie of Amphenol) ? 

Best regards,

**Comment by Rbb666** [comment]
@JiaBing912

**Comment by Shadowyingjian** [comment]
Hi，The part number of CN5 connector is X0802WVS-40AS-LPV01 ,and you can buy it with https://item.szlcsc.com/3244579.html.

**Comment by Shadowyingjian** [comment]
邮件已收到，谢谢！——来自QQ邮箱客户端
